name: flutter_app_example_support
deploy_to: none

environment:
  sdk: '>=2.5.0-dev <4.0.0'

dependencies:
  tekartik_build_utils:
    git:
      url: git://github.com/tekartik/build_utils.dart
      ref: dart2
    version: '>=0.7.0'
  tekartik_travis_ci_flutter:
    git:
      url: git://github.com/tekartik/travis_ci_flutter.dart
      ref: dart2
    version: '>=0.1.0'

dependency_overrides:
#  tekartik_build_utils:
#    path: ../../../tekartik/build_utils.dart