language: dart
sudo: required
dist: trusty
dart:
  - stable
  - dev
before_script:
  - pushd support
  - pub run tekartik_travis_ci_flutter:install
  - source $(pub run tekartik_travis_ci_flutter:env)
script:
  - dart tool/travis.dart
